model:
  name: transformer_kws
  layers: 12
  heads: 2
  mlp_dim: 512
  num_output_classes: 11
  embedding_dim: 256
  norm_type: postnorm
  dropout: 0.1

data:
  time_window: 100
  frequency: 40
  patch_size_t: 20
  patch_size_f: 8

training:
  batch: 512
  lr: 3e-4
  save_dir_tr: ./outputs/trainer
  save_dir_wandb: ./outputs/wandb
  model_path: ./outputs/models
  epochs: 50

dataset:
  sample_rate: 16000
  destination: ./kws_transformer/dataset

mfcc_settings:
  sample_rate: 16000
  n_mfcc: 40
  n_mels: 80
  n_fft: 480
  hop_length: 161